### PR TITLE
Fix exercise

### LINKED ISSUE #192: Exercise
Solve all bugs from EXERCISE. All endpoints
+ issue for every bug found !! include steps (for all)

### PR DESCRIPTION
**Pull request by AdrianSofariu**
This pull request introduces significant changes to improve the handling of polymorphic exercises, enhance JSON serialization/deserialization, and update the database schema. The key updates include enabling polymorphic support for exercises, introducing utility classes for JSON operations, and modifying the database schema to support new features.

### Polymorphic Support for Exercises
* Updated `ExamController` and `ExerciseController` to handle polymorphic exercise types during serialization and deserialization. This includes changes to methods like `AddExam`, `GetExam`, and `AddExercise` to process exercises dynamically based on their type (`Flashcard`, `MultipleChoice`, etc.) using JSON discriminators. [[1]](diffhunk://#diff-7537690083a215b61894a43fa0a77ea6b4e708e7b99a584a557c98f39bfc8775L33-R43) [[2]](diffhunk://#diff-7537690083a215b61894a43fa0a77ea6b4e708e7b99a584a557c98f39bfc8775L56-R99) [[3]](diffhunk://#diff-cc4f36456797851380da36bea07a161e43e7c6be74e82ff607f98d2ddd3c6d8eL147-R207)
* Introduced `ExerciseMerger` to merge exercises of the same type while preserving their unique properties.

### JSON Serialization and Deserialization Utilities
* Added `JsonSerializationUtil` to streamline serialization and deserialization of exams and exercises, supporting polymorphic types and ensuring compatibility with the repository.
* Introduced `ExamDTO` to represent exam data with proper JSON serialization attributes, ensuring null values are included during serialization.

### Database Schema Updates
* Renamed a migration file and updated it to include new entities like `CourseTag` and additional properties (e.g., `Type`) for exercises. Adjusted primary key and foreign key relationships to support the new schema. [[1]](diffhunk://#diff-24ab5c0de292832e5eb9416f19f629c4ce36e3372db9db91a93a11f8fe942ad5L15-R16) [[2]](diffhunk://#diff-24ab5c0de292832e5eb9416f19f629c4ce36e3372db9db91a93a11f8fe942ad5R90-R104) [[3]](diffhunk://#diff-24ab5c0de292832e5eb9416f19f629c4ce36e3372db9db91a93a11f8fe942ad5R530-R548)
* Changed the `AnswerModelId` in `MultipleChoiceAnswerModel` from `string` to `int` and enabled identity column generation for it.

### Codebase Enhancements
* Updated `CreateExerciseDto` to include a `Type` property for identifying exercise types during creation.
* Removed unused `CodeAnalysisRuleSet` from the project file and added a folder for migrations. [[1]](diffhunk://#diff-736f4af35357c8b80f5d0a7c7817866a437e223676a140e82f963f700eaee4aaL7) [[2]](diffhunk://#diff-736f4af35357c8b80f5d0a7c7817866a437e223676a140e82f963f700eaee4aaR38)

### Minor Updates
* Adjusted `QuizController` to accept quizzes via `FromBody` instead of `FromForm` for consistency with other controllers.

### CODE REVIEW

File: Duo/ViewModels/ManageExercisesViewModel.cs [hunk 1]
```diff
@@ -33,7 +33,13 @@ public ManageExercisesViewModel()
             DeleteExerciseCommand = new RelayCommandWithParameter<Exercise>(exercise => _ = DeleteExercise(exercise));
 
             InitializeViewModel();
-            _ = Task.Run(async () => await LoadExercisesAsync());
+            LoadExercises();
```
Comment (UjfalusiAbel) [inline Duo/ViewModels/ManageExercisesViewModel.cs]: Does this really work? wrapping async function into another and no trunning async doesn't seem like a good idea

File: Duo/Helpers/JsonSerializationUtil.cs [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+                WriteIndented = true,
+                PropertyNameCaseInsensitive = true,
+            };
+
+            var examDto = new
+            {
+                exam.Id,
+                exam.SectionId,
+                Exercises = exam.Exercises.Select(e => e.ExerciseId).ToList(),
+                // MaxExercises = exam.Exercises.Count,
```
Comment (UjfalusiAbel) [inline Duo/Helpers/JsonSerializationUtil.cs]: Please clean it up, delete commented code

File: Duo/Services/ExerciseServiceProxy.cs [hunk 3]
```diff
@@ -45,6 +47,20 @@ public async Task CreateExercise(Exercise exercise)
...
+                    PropertyNameCaseInsensitive = true,
+                    WriteIndented = true,
+                });
+
+                if (idObj != null)
+                {
+                    exercise.ExerciseId = idObj.ExerciseId;
+                }
+
                 /*switch (exercise.Type)
```
Comment (UjfalusiAbel) [inline Duo/Services/ExerciseServiceProxy.cs]: delete commented code

**Review by UjfalusiAbel — CHANGES_REQUESTED** [review]
Look into that async please
