### PR TITLE
160 task add try catch blocks in quizservice for robust error handling

### LINKED ISSUE #160: Task: Add try-catch blocks in QuizService for robust error handling
Requirements:

- Add try-catch blocks to all public service methods that perform data access or critical logic.

- Ensure that all caught exceptions are:

- Logged appropriately (with context).

- Translated into meaningful error messages for the client (where applicable).

- Return consistent and safe API responses in failure cases.

- DO NOT allow unhandled exceptions to bubble up from the service layer under any circumstance.

### PR DESCRIPTION
**Pull request by ArturZsigmond**
Stylecop is also good with the modifications I made, no errors from that

### CODE REVIEW

**Comment by ArturZsigmond** [comment]
Abel, can you please look inside the file QuizService, line 32, at method GetAllAvailableExams and explain why the true return is commented? the function has an implementation. Please require changes with details regarding that method.

**Review by UjfalusiAbel — APPROVED** [review]
Nice additions

**Comment by UjfalusiAbel** [comment]
Please modify QuizServiceProxy because it has problems with the URL and it needs modifications

File: Duo/Services/QuizServiceProxy.cs [hunk 1]
```diff
@@ -18,108 +20,284 @@ public QuizServiceProxy(HttpClient httpClient)
 
         public async Task<List<Quiz>> GetAsync()
         {
-            return await httpClient.GetFromJsonAsync<List<Quiz>>("quiz/list");
+            try
+            {
+                var result = await httpClient.GetFromJsonAsync<List<Quiz>>("quiz/list");
```
Comment (UjfalusiAbel) [inline Duo/Services/QuizServiceProxy.cs:25]: Change URL

**Review by UjfalusiAbel — COMMENTED** [review]
Please change URL in QuizServiceProxy in order to be correct
