### PR TITLE
162 task add try catch blocks in SectionService for robust error handling

### LINKED ISSUE #162: Task: Add try-catch blocks in SectionService for robust error handling
Requirements:

Add try-catch blocks to all public service methods that perform data access or critical logic.

Ensure that all caught exceptions are:

Logged appropriately (with context).

Translated into meaningful error messages for the client (where applicable).

Return consistent and safe API responses in failure cases.

DO NOT allow unhandled exceptions to bubble up from the service layer under any circumstance

### PR DESCRIPTION
**Pull request by CristiSlv1**

### CODE REVIEW

File: Duo/Services/SectionServiceProxy.cs [hunk 1]
```diff
@@ -15,55 +17,125 @@ public SectionServiceProxy(HttpClient httpClient)
 
     public async Task<int> AddSection(Section section)
     {
-        var response = await httpClient.PostAsJsonAsync("api/sections/add", section);
-        response.EnsureSuccessStatusCode();
-        return await response.Content.ReadFromJsonAsync<int>();
+        try
+        {
+            var response = await httpClient.PostAsJsonAsync("api/sections/add", section);
```
Comment (UjfalusiAbel) [inline Duo/Services/SectionServiceProxy.cs]: Wrong url, please don't commit while untried

File: Duo/Services/SectionServiceProxy.cs [hunk 2]
```diff
@@ -15,55 +17,125 @@ public SectionServiceProxy(HttpClient httpClient)
...
+            throw new SectionServiceProxyException("Failed to add section via proxy.", ex);
+        }
     }
 
     public async Task<int> CountSectionsFromRoadmap(int roadmapId)
     {
-        return await httpClient.GetFromJsonAsync<int>($"api/sections/count/{roadmapId}");
+        try
+        {
+            return await httpClient.GetFromJsonAsync<int>($"api/sections/count/{roadmapId}");
```
Comment (UjfalusiAbel) [inline Duo/Services/SectionServiceProxy.cs]: Wrong url, please don't commit while untried

File: Duo/Services/SectionServiceProxy.cs [hunk 3]
```diff
@@ -15,55 +17,125 @@ public SectionServiceProxy(HttpClient httpClient)
...
+            throw new SectionServiceProxyException($"Failed to count sections for roadmap ID {roadmapId}.", ex);
+        }
     }
 
     public async Task DeleteSection(int sectionId)
     {
-        await httpClient.DeleteAsync($"api/sections/{sectionId}");
+        try
+        {
+            await httpClient.DeleteAsync($"api/sections/{sectionId}");
```
Comment (UjfalusiAbel) [inline Duo/Services/SectionServiceProxy.cs]: Wrong url, please don't commit while untried

**Review by UjfalusiAbel — CHANGES_REQUESTED** [review]
Please fix url problems and next time try if it connects to API not just make a PR

**Review by UjfalusiAbel — APPROVED** [review]
Approved
